### ISSUE TITLE
'Ask ChatGPT' button always disabled

### ISSUE THREAD

**Issue by devheyaragon** [FlowFuse/node-red-function-gpt#23]
### Current Behavior

First of all:  this Node is an excellent idea, KUDOS!

I wanted to try it immediately as it would be an excellent help to our customers, electricians not necessarily skilled in programming.

I have installed the node and configured the OpenAI API key. Not sure what I should put in the organization field, for now, I've set it to 'Personal'. And deployed.

However the 'Ask ChatGPT' button always disabled remains disabled.

### Steps To Reproduce

Install and configure as described.

### Environment

- FlowForge version: -
- NodeRED 3.1
- Node.js version: v18
- npm version:
- Platform/OS: Debian
- Browser: Brave

**Comment by joepavitt** [comment]
Hi @devheyaragon - thanks for the feedback here. Our README is missing a key piece of guidance re: organisation ID, I'll get that added shortly, but in the mean time, the Org ID can be found here:

https://platform.openai.com/account/org-settings

<img width="1203" alt="Screenshot 2023-09-21 at 09 35 43" src="https://github.com/flowforge/node-red-function-gpt/assets/99246719/2f962724-e2af-48e5-9f6d-af802dae79b7">

**Comment by joepavitt** [comment]
This is getting into Node-RED core, which is not my area. @Steve-Mcl will be able to advise accordingly here.

**Comment by Steve-Mcl** [comment]
> VM405:704 Uncaught ReferenceError: monaco is not defined

What version of Node-RED are you using?

**Comment by joepavitt** [comment]
> What version of Node-RED are you using?

He listed `3.1` in the original issue

**Comment by devheyaragon** [comment]
I'm using latest stable v.3.1.0

**Comment by Steve-Mcl** [comment]
My apologies I missed that,  Thanks.

Now that I know this, can you do 2 things.  

### No. 1
* Open your browser dev tools console (Usually F12 or right-click inspect)
* refresh node-red editor & tell me what you see in the console. 
* e.g  ![image](https://github.com/flowforge/node-red-function-gpt/assets/44235289/af2e9942-e70f-4ab4-a5b1-deace40529fb)
* Please include any `red` errors


### No. 2
* Provide a copy of your node-red start up log (from "Welcome to Node-RED" message upto the "
Started flows" message)
  * _feel free to XXXXX anything you feel is sensitive info_

<br> 

Alternatively, provide a copy of the "System info" from the action list: `CTRL+SHIFT+P` -> "system info" -> copy to clipboard
![chrome_WA2RURdLpv](https://github.com/flowforge/node-red-function-gpt/assets/44235289/39e41acd-af99-484f-87c8-c67a6121e7f7)

**Comment by devheyaragon** [comment]
Hello, and thank you for looking into this!
As noted earlier, the "*VM405:704 Uncaught ReferenceError: monaco is not
defined*" appears as soon as I open the Edit function-gpt node.
I'm running a stand-alone Node-RED on a local computer
[image: image.png]
{
    "report": "diagnostics",
    "scope": "basic",
    "time": {
        "utc": "Fri, 22 Sep 2023 06:19:00 GMT",
        "local": "9/22/2023, 8:19:00 AM"
    },
    "intl": {
        "locale": "en-US",
        "timeZone": "Europe/Paris"
    },
    "nodejs": {
        "version": "v18.18.0",
        "arch": "arm64",
        "platform": "linux",
        "memoryUsage": {
            "rss": 139378688,
            "heapTotal": 74801152,
            "heapUsed": 69231376,
            "external": 3786037,
            "arrayBuffers": 1887997
        }
    },
    "os": {
        "wsl": false,
        "totalmem": 4024745984,
        "freemem": 2848792576,
        "arch": "arm64",
        "loadavg": [
            0.01,
            0.19,
            0.24
        ],
        "platform": "linux",
        "release": "4.19.193",
        "type": "Linux",
        "uptime": 15529.06,
        "version": "#3 SMP PREEMPT Thu Aug 25 21:05:15 CST 2022"
    },
    "runtime": {
        "version": "3.1.0",
        "isStarted": true,
        "flows": {
            "state": "start",
            "started": true
        },
        "modules": {
            "node-red": "3.1.0",
            "node-red-contrib-https": "2.0.0",
            "node-red-contrib-interval": "0.0.1",
            "node-red-contrib-join-wait": "0.5.3",
            "node-red-contrib-knx-ultimate": "1.4.18",
            "node-red-dashboard": "3.5.0",
            "node-red-node-base64": "0.3.0",
            "node-red-node-ui-table": "0.4.3",
            "node-red-contrib-enocean": "0.8.5",
            ***@***.***/node-red-function-gpt": "0.2.1"
        },
        "settings": {
            "available": true,
            "apiMaxLength": "UNSET",
            "disableEditor": false,
            "contextStorage": {
                "default": {
                    "module": "localfilesystem"
                }
            },
            "debugMaxLength": 1000,
            "editorTheme": {
                "palette": {},
                "projects": {
                    "enabled": false,
                    "workflow": {
                        "mode": "manual"
                    }
                },
                "codeEditor": {
                    "lib": "ace",
                    "options": {
                        "theme": "vs"
                    }
                },
                "menu": {
                    "menu-item-help": {
                        "label": "Node-RED Library",
                        "url": "https://github.com/devheyaragon/nodered"
                    }
                }
            },
            "flowFile": "flows.json",
            "mqttReconnectTime": 15000,
            "serialReconnectTime": 15000,
            "socketReconnectTime": "UNSET",
            "socketTimeout": "UNSET",
            "tcpMsgQueueSize": "UNSET",
            "inboundWebSocketTimeout": "UNSET",
            "runtimeState": "UNSET",
            "adminAuth": "SET",
            "httpAdminRoot": "/",
            "httpAdminCors": "UNSET",
            "httpNodeAuth": "UNSET",
            "httpNodeRoot": "/",
            "httpNodeCors": "UNSET",
            "httpStatic": "UNSET",
            "httpStaticRoot": "UNSET",
            "httpStaticCors": "UNSET",
            "uiHost": "SET",
            "uiPort": "SET",
            "userDir": "SET",
            "nodesDir": "UNSET"
        }
    }
}

**Comment by devheyaragon** [comment]
Hello, did the provided debug information help, can I provide more?

**Comment by Steve-Mcl** [comment]
> "codeEditor": { "lib": "ace",

Is there any reason you are using the old (soon to be depreciated) ACE editor?

It doesnt support many new features of JavaScript lang.

If you change to monaco, this will work for you.

**Comment by Steve-Mcl** [comment]
> > "codeEditor": { "lib": "ace",
> 
> Is there any reason you are using the old (soon to be depreciated) ACE editor?
> 
> It doesnt support many new features of JavaScript lang.
> 
> If you change to monaco, this will work for you.

NOTE: That ↑ does not mean we won't be making it editor agnostic, just that time is the enemy. It will get updated (hopefully soon)

**Comment by devheyaragon** [comment]
Thank you for the reply !
I will switch to Monaco and try it again.
And thank you for pointing at the Monaco editor, I wasn't aware..
The reason we're still using the default ace editor is we have many users
out there running various versions of Node-RED.

**Comment by joepavitt** [comment]
@devheyaragon - any update here? Assume switching to `monaco` editor did the trick?

**Comment by devheyaragon** [comment]
Yes, we switched to monaco so it is no longer an issue from our point of
view, Thanks for the support
